# Flujo de trabajo CI/CD para un sistema de gobernanza basado en blockchain

name: Governance System CI

on:
  # Ejecutar el flujo de trabajo en eventos de push o pull request en la rama "main"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Permitir ejecución manual desde la pestaña de Actions
  workflow_dispatch:

jobs:
  # Trabajo para construir y probar el sistema de gobernanza
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v4

      # Paso 2: Instalar Node.js para manejar scripts frontend
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Paso 3: Instalar dependencias del proyecto (asumiendo un archivo package.json)
      - name: Instalar dependencias
        run: npm install

      # Paso 4: Ejecutar linters y pruebas del frontend (JavaScript y CSS)
      - name: Ejecutar linters y pruebas del frontend
        run: |
          npm run lint
          npm run test

      # Paso 5: Configurar el entorno de desarrollo para Solidity (Truffle o Hardhat)
      - name: Instalar Hardhat o Truffle
        run: |
          npm install --save-dev hardhat  # O truffle si se utiliza Truffle

      # Paso 6: Compilar los contratos Solidity
      - name: Compilar contratos Solidity
        run: |
          npx hardhat compile  # O truffle compile si se usa Truffle

      # Paso 7: Ejecutar pruebas de los contratos en Hardhat o Truffle
      - name: Ejecutar pruebas de contratos
        run: |
          npx hardhat test  # O truffle test

      # Paso 8: (Opcional) Desplegar los contratos en una red de prueba (por ejemplo, Rinkeby)
      - name: Desplegar contratos en red de prueba
        run: |
          npx hardhat run scripts/deploy.js --network rinkeby  # Ejemplo de red de prueba

      # Paso 9: Notificar éxito al finalizar el proceso
      - name: Notificar éxito
        run: echo "¡El sistema de gobernanza ha sido construido y desplegado exitosamente!"
