# Flujo de trabajo CI/CD

name: Governance System CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v4

      # Paso 2: Instalar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Paso 3: Instalar dependencias
      - name: Instalar dependencias
        run: npm install

      # Paso 4: Ejecutar linters y pruebas del frontend
      - name: Ejecutar linters y pruebas del frontend
        run: |
          npm run lint
          npm run test
