# Flujo de trabajo CI/CD para un sistema de gobernanza basado en blockchain

name: Governance System CI

on:
  # Ejecutar el flujo de trabajo en eventos de push o pull request en la rama "main"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Permitir ejecución manual desde la pestaña de Actions
  workflow_dispatch:

jobs:
  # Trabajo para construir y probar el sistema de gobernanza
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v4

      # Paso 2: Instalar Node.js para manejar scripts frontend
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Paso 3: Cambiar el directorio a la carpeta frontend (si es necesario)
      - name: Navegar a la carpeta frontend
        run: cd frontend  # Cambiar a la carpeta donde está package.json

      # Paso 4: Instalar dependencias del proyecto (package.json)
      - name: Instalar dependencias
        run: npm install

      # Paso 5: Ejecutar linters y pruebas del frontend (JavaScript y CSS)
      - name: Ejecutar linters y pruebas del frontend
        run: |
          npm run lint
          npm run test

      # Paso 6: Cambiar el directorio a la carpeta de contratos Solidity (si es necesario)
      - name: Navegar a la carpeta de contratos
        run: cd ../contracts  # Cambiar a la carpeta donde están los contratos Solidity

      # Paso 7: Instalar Hardhat
      - name: Instalar Hardhat
        run: |
          npm install --save-dev hardhat

      # Paso 8: Compilar los contratos Solidity
      - name: Compilar contratos Solidity
        run: |
          npx hardhat compile

      # Paso 9: Ejecutar pruebas de los contratos en Hardhat
      - name: Ejecutar pruebas de contratos
        run: |
          npx hardhat test

      # Paso 10: (Opcional) Desplegar los contratos en una red de prueba
      - name: Desplegar contratos en red de prueba
        run: |
          npx hardhat run scripts/deploy.js --network rinkeby

      # Paso 11: Notificar éxito al finalizar el proceso
      - name: Notificar éxito
        run: echo "¡El sistema de gobernanza ha sido construido y desplegado exitosamente!"
